version: 2


sources:
  
  - name: raw_taxi
    description: "Données brutes Airbnb chargées depuis le repository Git"
    database: NYC_TAXI_DB
    schema: RAW
    tables:
    - name: YELLOW_TAXI_TRIPS
 